"""AGLedger SDK: Accountability and audit infrastructure for agentic systems."""

from agledger._client import AgledgerClient, AsyncAgledgerClient
from agledger._http import RateLimitInfo, SDK_VERSION
from agledger._errors import (
    AgledgerError,
    ConfigurationError,
    APIConnectionError,
    APIError,
    APITimeoutError,
    AuthenticationError,
    BadRequestError,
    ConflictError,
    NotFoundError,
    PaginationLimitError,
    PermissionDeniedError,
    RateLimitError,
    SignatureAlgorithmUnavailableError,
    SignatureVerificationError,
    UnprocessableError,
)
from agledger.record_lifecycle import (
    RECORD_TRANSITIONS,
    TERMINAL_STATUSES,
    can_transition_to,
    get_valid_transitions,
    is_terminal_status,
)
from agledger.scopes import (
    ApiKeyRole,
    SCOPE_PROFILES,
    ScopeProfile,
    ScopeProfileName,
    Scopes,
    default_profile_for,
)
from agledger.types import (
    AccountProfile,
    AgentCapabilities,
    AgentProfile,
    AiImpactAssessment,
    AuditActor,
    AuditExportEntry,
    AuditExportMetadata,
    AuditStreamResult,
    BulkCreateResult,
    BulkCreateResultItem,
    BulkCreateSummary,
    ComplianceExport,
    ComplianceRecord,
    ConformanceResponse,
    Dispute,
    DisputeEvidence,
    DisputeResponse,
    DisputeStatus,
    EntityReference,
    Event,
    HealthResponse,
    GateEvaluationResult,
    GateMode,
    GateStatus,
    NextStep,
    OperatingMode,
    Completion,
    CompletionSettlementSignal,
    Page,
    RecordAuditExport,
    RecordIntegrity,
    RecordReadCompletion,
    RecordRow,
    RecordStatus,
    RecordTransitionAction,
    RecordType,
    ReputationScore,
    StatusComponent,
    StatusResponse,
    OrgReadsCheckpoint,
    OrgReadsInclusionProof,
    VaultCheckpoint,
    VaultCheckpointChain,
    SettlementSignalSummary,
    SignedStatement,
    Verdict,
    VerdictResult,
    VerdictStatistics,
    VerificationKey,
    VerificationKeysResponse,
    Webhook,
    WebhookEventType,
    WebhookTestResult,
)

# Single source of truth lives in `_http.SDK_VERSION` (derived from installed
# package metadata), re-exported here so `agledger.__version__`, the User-Agent
# header, and the published distribution can never drift apart.
__version__ = SDK_VERSION
__all__ = [
    "AgledgerClient",
    "AsyncAgledgerClient",
    "RateLimitInfo",
    # Errors
    "AgledgerError",
    "ConfigurationError",
    "APIError",
    "AuthenticationError",
    "PermissionDeniedError",
    "NotFoundError",
    "BadRequestError",
    "UnprocessableError",
    "RateLimitError",
    "ConflictError",
    "APIConnectionError",
    "APITimeoutError",
    "PaginationLimitError",
    "SignatureAlgorithmUnavailableError",
    "SignatureVerificationError",
    # Scopes
    "ApiKeyRole",
    "Scopes",
    "ScopeProfile",
    "SCOPE_PROFILES",
    "ScopeProfileName",
    "default_profile_for",
    # Record lifecycle
    "RECORD_TRANSITIONS",
    "TERMINAL_STATUSES",
    "can_transition_to",
    "get_valid_transitions",
    "is_terminal_status",
    # Types: Records
    "RecordRow",
    "RecordIntegrity",
    "RecordStatus",
    "RecordTransitionAction",
    "RecordType",
    "Completion",
    "CompletionSettlementSignal",
    "OperatingMode",
    "GateMode",
    "GateEvaluationResult",
    "GateStatus",
    # Types: Disputes
    "Dispute",
    "DisputeEvidence",
    "DisputeResponse",
    "DisputeStatus",
    "EntityReference",
    # Types: Webhooks
    "Webhook",
    "WebhookEventType",
    "WebhookTestResult",
    # Types: Reputation / Events
    "ReputationScore",
    "Event",
    # Types: Identity
    "AccountProfile",
    "AgentProfile",
    "AgentCapabilities",
    # Types: Discovery / metadata
    "NextStep",
    "HealthResponse",
    "StatusComponent",
    "StatusResponse",
    "ConformanceResponse",
    # Types: Audit / Vault
    "AuditActor",
    "AuditExportEntry",
    "AuditExportMetadata",
    "AuditStreamResult",
    "RecordAuditExport",
    "RecordReadCompletion",
    "SignedStatement",
    "SettlementSignalSummary",
    "Verdict",
    "VerdictResult",
    "VerdictStatistics",
    "VerificationKey",
    "VerificationKeysResponse",
    "OrgReadsCheckpoint",
    "OrgReadsInclusionProof",
    "VaultCheckpoint",
    "VaultCheckpointChain",
    # Types: Bulk operations
    "BulkCreateResult",
    "BulkCreateResultItem",
    "BulkCreateSummary",
    # Types: Pagination
    "Page",
    # Types: Compliance
    "ComplianceRecord",
    "ComplianceExport",
    "AiImpactAssessment",
]
