"""SDK <-> API Schema-Field Parity Test (Python).

The field-level analogue of test_parity.py, and the Python mirror of the TS
``schema-parity.test.ts``. ``routes.json`` pins the route surface; the shared
``schema-fields.json`` snapshot pins the per-model FIELD surface. Together they
catch the two ways the API drifts from the SDK — endpoints AND field shapes.

This guard exists because route-only parity silently missed a full minor's worth
of field renames/additions (0.26.x). A clean route diff (194/194) hid all of it.
The TS SDK gained this guard in the 0.26.x wave; Python had only hand-written
``test_response_contract.py`` regressions for specific past bugs — no snapshot
diff. This closes that TS/Python asymmetry: the Python models are now held to
the same field snapshot, so the moment the API adds/renames a field a mapped
model doesn't carry, this fails too.

Comparison is on WIRE names (the camelCase the API emits): each Pydantic field's
wire name is its ``alias`` if set, else the attribute name. We introspect
``model_fields`` at runtime rather than parsing source — Pydantic already knows
the alias, so there is nothing to re-derive or get wrong.

The snapshot is vendored into this repo at ``tests/parity/schema-fields.json``
(single source upstream, regenerated by the weekly update-route-manifest
workflow and synced here); skip cleanly when it is unavailable (PyPI install).
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from pydantic import BaseModel

from agledger.types import (
    Completion,
    Dispute,
    DisputeEvidence,
    EntityReference,
    NextStep,
    RecordRow,
    ReputationScore,
    Webhook,
)

_SNAPSHOT_PATH = Path(__file__).resolve().parent / "parity" / "schema-fields.json"

# API component -> Python model. Mirrors the TS ALIASES exactly, by design: the
# Python model names track the TS interface names. The two diverge from the API
# component name where the SDK wraps or renames — the flat ``DisputeResponse``
# component is the SDK's ``Dispute`` (the SDK DisputeResponse is a
# {dispute, evidence} GET wrapper); ``WebhookSubscription`` is ``Webhook``;
# ``NextStepAction`` is ``NextStep``.
#
# ``WebhookDelivery`` is intentionally absent: Python's ``list_deliveries``
# returns ``Page[dict[str, Any]]`` (untyped rows), not a typed model — there is
# nothing to drift-check. TS models it; Python doesn't. Tracked as a known,
# deliberate divergence, not a gap this guard should fail on.
ALIASES: dict[str, type[BaseModel]] = {
    "RecordRow": RecordRow,
    "Completion": Completion,
    "DisputeResponse": Dispute,
    "DisputeEvidence": DisputeEvidence,
    "WebhookSubscription": Webhook,
    "ReputationScore": ReputationScore,
    "EntityReference": EntityReference,
    "NextStepAction": NextStep,
}

# Snapshot components the Python SDK deliberately does NOT model with a typed
# class (so there is nothing to field-check). Every snapshot component must be
# either in ALIASES or here — the coverage test below enforces that, so a NEW
# API component can't be silently skipped on the Python side (a future typed
# model for any of these must move it from here into ALIASES).
EXCLUDED_COMPONENTS: set[str] = {
    "WebhookDelivery",  # returned as Page[dict]; no typed model (see ALIASES note)
    "ErrorResponse",    # error envelope, surfaced via the exception hierarchy, not a data model
    "RateLimitError",   # ditto — error shape, not a response model
}

# SDK-only fields that are intentional, not drift. Keyed by API component name.
# Keep SHORT and justify every entry. Mirrors the TS ALLOWED_SDK_ONLY.
ALLOWED_SDK_ONLY: dict[str, set[str]] = {
    # recentHistory is hydrated from the separate reputation-history endpoint.
    "ReputationScore": {"recentHistory"},
}


def _wire_fields(model_cls: type[BaseModel]) -> set[str]:
    """The wire (camelCase) field names a model declares — alias if set, else
    the attribute name. This is what the model can deserialize by name from an
    API response."""
    return {(fi.alias or name) for name, fi in model_cls.model_fields.items()}


@pytest.fixture(scope="module")
def snapshot() -> dict[str, list[str]]:
    if not _SNAPSHOT_PATH.exists():
        pytest.skip(f"schema-fields snapshot not available at {_SNAPSHOT_PATH} (standalone checkout)")
    data = json.loads(_SNAPSHOT_PATH.read_text())
    schemas = data.get("schemas", {})
    assert data.get("schemaCount") == len(schemas), "snapshot schemaCount disagrees with schemas map"
    return schemas


@pytest.mark.parametrize(("api_name", "model_cls"), list(ALIASES.items()))
def test_model_covers_every_api_field(
    snapshot: dict[str, list[str]], api_name: str, model_cls: type[BaseModel]
) -> None:
    """The Python model must carry every field the API component declares —
    else a consumer can't see it as a typed attribute (it lands in extras)."""
    api_fields = snapshot.get(api_name)
    assert api_fields is not None, f"API component {api_name} missing from snapshot"
    wire = _wire_fields(model_cls)
    missing = [f for f in api_fields if f not in wire]
    assert not missing, (
        f"{model_cls.__name__} is missing API {api_name} fields "
        f"(consumers can't see them): {missing}"
    )


@pytest.mark.parametrize(("api_name", "model_cls"), list(ALIASES.items()))
def test_model_has_no_stale_fields(
    snapshot: dict[str, list[str]], api_name: str, model_cls: type[BaseModel]
) -> None:
    """The Python model must not declare fields the API no longer returns
    (except the short, justified SDK-only allowlist)."""
    api_fields = snapshot.get(api_name)
    assert api_fields is not None, f"API component {api_name} missing from snapshot"
    allowed = ALLOWED_SDK_ONLY.get(api_name, set())
    api_set = set(api_fields)
    stale = [f for f in _wire_fields(model_cls) if f not in api_set and f not in allowed]
    assert not stale, (
        f"{model_cls.__name__} declares fields absent from the API {api_name} "
        f"schema (stale or needs allowlisting): {stale}"
    )


def test_every_snapshot_component_is_mapped_or_excluded(snapshot: dict[str, list[str]]) -> None:
    """Every component in the shared snapshot must be either mapped (ALIASES) or
    explicitly excluded. Without this, a NEW API component added to the snapshot
    would be field-checked by the TS guard but SILENTLY skipped here (the per-
    model tests only iterate ALIASES keys), reintroducing the exact blind spot
    this guard exists to close. A failure means: add the component to ALIASES
    with its Python model, or to EXCLUDED_COMPONENTS with a reason."""
    accounted = set(ALIASES) | EXCLUDED_COMPONENTS
    uncovered = sorted(set(snapshot) - accounted)
    assert not uncovered, (
        f"snapshot components neither mapped nor excluded: {uncovered}. "
        f"Add each to ALIASES (with a Python model) or EXCLUDED_COMPONENTS (with a reason)."
    )
